Add (unratified) BF16(Zfbfmin/Zvfbfmin/Zvfbfwma) extensions.
riscv/riscv-opcodes pull request #174
Opened 2023-04-14 15:08 UTC by liweiwei90

Currently fcvt.bf16.s instruction in Zfbfmin has conflict encoding with fround.h instruction in Zfa extension.

2023-04-14 21:03 UTC, aswaterman commented
@liweiwei90 I recommended to @kdockser that rs2=8 be used for the fcvt.bf16.s instruction to avoid this conflict, but I don't know if the spec has been updated yet.

@kdockser can you review?

2023-04-14 21:03 UTC, aswaterman requested changes
Don't merge until the opcode conflict is resolved.  LGTM otherwise.

2023-04-15 00:33 UTC, liweiwei90 commented
> @liweiwei90 I recommended to @kdockser that rs2=8 be used for the fcvt.bf16.s instruction to avoid this conflict, but I don't know if the spec has been updated yet.
Yeah. The didn't find the closed issue for this problem. The spec has not been updated yet, but may be updated soon.

2023-04-19 20:43 UTC, aswaterman approved these changes

2023-04-19 23:40 UTC, merged